version: "3.3"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/aspnetcore-debug/Dockerfile
    image: aspnetcore-debug
    container_name: votingapp
    volumes: 
      - ./src/VotingApp.Api/bin/build/:/app
    ports:
      - 5000:80