
version: "3.3"

services:
  app:
    image: ${REGISTRY}votingapp:${TAG}
    build:
      context: ${BUILD_CONTEXT}
      dockerfile: ./src/VotingApp.Api/Dockerfile
    container_name: votingapp
    ports:
      - 80:80